# Generated by Django 6.0.1 on 2026-01-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Imię lekarza.', max_length=50)),
                ('last_name', models.CharField(help_text='Nazwisko lekarza.', max_length=50)),
                ('specialty', models.CharField(help_text='Specjalizacja lekarza.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(help_text='Nazwa procedury medycznej.', max_length=100)),
                ('description', models.TextField(help_text='Opis procedury medycznej.')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Koszt procedury medycznej.', max_digits=10)),
                ('date', models.DateTimeField(help_text='Data i czas wykonania procedury.')),
                ('doctor', models.ForeignKey(help_text='Lekarz wykonujący procedurę.', on_delete=django.db.models.deletion.CASCADE, to='bazam.doctor')),
            ],
        ),
    ]
