# Generated by Django 6.0.1 on 2026-01-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(help_text='Imię lekarza.', max_length=50)),
                ('Nazwisko', models.CharField(help_text='Nazwisko lekarza.', max_length=50)),
                ('Specjalizacja', models.CharField(help_text='Specjalizacja lekarza.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(help_text='Imię osoby.', max_length=50)),
                ('nazwisko', models.CharField(help_text='Nazwisko osoby.', max_length=50)),
                ('stanowisko', models.CharField(help_text='Stanowisko osoby w organizacji.', max_length=100)),
                ('data_dodania', models.DateTimeField(auto_now_add=True, help_text='Data dodania rekordu.')),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(help_text='Imię pacjenta.', max_length=50)),
                ('Nazwisko', models.CharField(help_text='Nazwisko pacjenta.', max_length=50)),
                ('data_urodzenia', models.DateField(help_text='Data urodzenia pacjenta.')),
                ('id_pacjenta', models.CharField(help_text='pesel pacjenta.', max_length=20, unique=True)),
                ('email_pacjenta', models.EmailField(help_text='Email pacjenta.', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalprocedures',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Zabiegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_zabiegu', models.CharField(help_text='Nazwa procedury medycznej.', max_length=100)),
                ('opis', models.TextField(help_text='Opis procedury medycznej.')),
                ('koszt', models.DecimalField(decimal_places=2, help_text='Koszt procedury medycznej.', max_digits=10)),
                ('data', models.DateTimeField(help_text='Data i czas wykonania procedury.')),
                ('lekarz', models.ForeignKey(help_text='Lekarz wykonujący procedurę.', on_delete=django.db.models.deletion.CASCADE, to='bazam.lekarz')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MedicalProcedures',
        ),
    ]
