# Generated by Django 6.0.1 on 2026-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(help_text='Imię osoby.', max_length=50)),
                ('nazwisko', models.CharField(help_text='Nazwisko osoby.', max_length=50)),
                ('stanowisko', models.CharField(help_text='Stanowisko osoby w organizacji.', max_length=100)),
                ('data_dodania', models.DateTimeField(auto_now_add=True, help_text='Data dodania rekordu.')),
            ],
        ),
    ]
