# Generated by Django 6.0.1 on 2026-01-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazam', '0002_osoba'),
    ]

    operations = [
        migrations.CreateModel(
            name='leki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_leku', models.CharField(help_text='Nazwa leku.', max_length=100)),
                ('opis', models.TextField(help_text='Opis leku.')),
                ('dawkowanie', models.CharField(help_text='Dawkowanie leku.', max_length=100)),
                ('producent', models.CharField(help_text='Producent leku.', max_length=100)),
            ],
        ),
    ]
