# Generated by Django 6.0.1 on 2026-01-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazam', '0002_lekarz_osoba_pacjent_remove_medicalprocedures_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa stanowiska, np. Kierownik.', max_length=100)),
                ('opis', models.TextField(blank=True, help_text='Opcjonalny opis stanowiska.', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='osoba',
            name='stanowisko',
            field=models.ForeignKey(blank=True, help_text='Stanowisko osoby w organizacji.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazam.stanowisko'),
        ),
    ]
